package com.observastack.orderservice.infrastructure.persistence;

import jakarta.persistence.CollectionTable;
import jakarta.persistence.Column;
import jakarta.persistence.ElementCollection;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.OrderColumn;
import jakarta.persistence.PostLoad;
import jakarta.persistence.PostPersist;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import org.springframework.data.domain.Persistable;

/**
 * JPA entity persisting a domain {@code Order}.
 *
 * <p>Deliberately independent of the domain aggregate — no domain type
 * appears anywhere in this class. {@link OrderMapper} is the only bridge
 * between the two, per ADR 0002.
 *
 * <p>Implements {@link Persistable} because the id is assigned by the
 * domain layer ({@code OrderId.newId()}), not generated by the database:
 * without this, Spring Data JPA's default {@code isNew()} check (id ==
 * null) always sees a non-null id and calls {@code merge()} instead of
 * {@code persist()} on every save, issuing a needless existence-checking
 * SELECT before every insert.
 *
 * <p>{@code lineItems} is fetched eagerly, against the JPA default: a
 * repository port is a domain-owned abstraction with no notion of a
 * Hibernate session, so an {@code Order} handed back by
 * {@code OrderRepositoryImpl} needs to be fully usable whether or not
 * the caller is still inside a transaction. Every call site today
 * happens to be transactional, so lazy loading hasn't broken anything
 * here yet — but inventory-service's equivalent collection hit exactly
 * this failure the moment a repository method got called from outside
 * an explicit transaction (see {@code ReservationEntity}), and nothing
 * stops the same call shape from happening here in a later milestone.
 */
@Entity
@Table(name = "orders")
public class OrderEntity implements Persistable<UUID> {

    @Id
    @Column(name = "id", nullable = false)
    private UUID id;

    @Transient
    private boolean isNew = true;

    @Column(name = "customer_id", nullable = false)
    private UUID customerId;

    // Currency lives on each line item's Money, not here — see
    // OrderLineItemEmbeddable. A top-level column would just be the same
    // fact stored twice, one copy of which could drift.
    @Column(name = "idempotency_key", nullable = false, unique = true)
    private String idempotencyKey;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    private OrderStatusEntity status;

    @Column(name = "created_at", nullable = false)
    private Instant createdAt;

    @Column(name = "placed_at")
    private Instant placedAt;

    @Column(name = "cancelled_at")
    private Instant cancelledAt;

    @ElementCollection(fetch = FetchType.EAGER)
    @CollectionTable(name = "order_line_items", joinColumns = @JoinColumn(name = "order_id"))
    @OrderColumn(name = "line_number")
    private List<OrderLineItemEmbeddable> lineItems = new ArrayList<>();

    protected OrderEntity() {
        // required by JPA
    }

    @Override
    public UUID getId() {
        return id;
    }

    @Override
    public boolean isNew() {
        return isNew;
    }

    @PostLoad
    @PostPersist
    void markNotNew() {
        this.isNew = false;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public UUID getCustomerId() {
        return customerId;
    }

    public void setCustomerId(UUID customerId) {
        this.customerId = customerId;
    }

    public String getIdempotencyKey() {
        return idempotencyKey;
    }

    public void setIdempotencyKey(String idempotencyKey) {
        this.idempotencyKey = idempotencyKey;
    }

    public OrderStatusEntity getStatus() {
        return status;
    }

    public void setStatus(OrderStatusEntity status) {
        this.status = status;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
    }

    public Instant getPlacedAt() {
        return placedAt;
    }

    public void setPlacedAt(Instant placedAt) {
        this.placedAt = placedAt;
    }

    public Instant getCancelledAt() {
        return cancelledAt;
    }

    public void setCancelledAt(Instant cancelledAt) {
        this.cancelledAt = cancelledAt;
    }

    public List<OrderLineItemEmbeddable> getLineItems() {
        return lineItems;
    }

    public void setLineItems(List<OrderLineItemEmbeddable> lineItems) {
        this.lineItems = lineItems;
    }
}
