package com.observastack.inventoryservice.infrastructure.persistence;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.PostLoad;
import jakarta.persistence.PostPersist;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;
import jakarta.persistence.Version;
import org.springframework.data.domain.Persistable;

/**
 * JPA entity persisting a domain {@code StockItem}.
 *
 * <p>{@code @Version} is the whole point of this milestone: it's what
 * makes {@link StockItemRepositoryImpl#update} detect a concurrent
 * modification instead of silently overwriting it — see the class
 * Javadoc there.
 *
 * <p>Implements {@link Persistable} for the same reason order-service's
 * {@code OrderEntity} does: the id (the SKU text) is assigned by the
 * caller, not generated by the database, so Spring Data's default
 * {@code isNew()} check (id == null) would always see a non-null id and
 * route every save through {@code merge()} instead of {@code persist()}.
 */
@Entity
@Table(name = "stock_items")
public class StockItemEntity implements Persistable<String> {

    @Id
    @Column(name = "sku", nullable = false)
    private String sku;

    @Transient
    private boolean isNew = true;

    @Column(name = "available_quantity", nullable = false)
    private int availableQuantity;

    @Version
    @Column(name = "version", nullable = false)
    private long version;

    protected StockItemEntity() {
        // required by JPA
    }

    @Override
    public String getId() {
        return sku;
    }

    @Override
    public boolean isNew() {
        return isNew;
    }

    @PostLoad
    @PostPersist
    void markNotNew() {
        this.isNew = false;
    }

    public String getSku() {
        return sku;
    }

    public void setSku(String sku) {
        this.sku = sku;
    }

    public int getAvailableQuantity() {
        return availableQuantity;
    }

    public void setAvailableQuantity(int availableQuantity) {
        this.availableQuantity = availableQuantity;
    }
}
